version: '3.8'
services:
    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - mysql:/var/lib/mysql
    postgres:
        image: postgres:14-alpine
        restart: always
        ports:
            - '5432:5432'
        expose:
            - '5432'
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    mysql:
    postgres: