version: '3.8'
services:
    mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'migration'
            MYSQL_USER: 'migration_test'
            MYSQL_PASSWORD: 'password@123'
            MYSQL_ROOT_PASSWORD: 'password@123'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - mysql:/var/lib/mysql
    postgres:
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_USER: 'migration'
            POSTGRES_PASSWORD: 'password@123'
            POSTGRES_DB: 'migration_test'
        ports:
            - '5432:5432'
        expose:
            - '5432'
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    mysql:
    postgres: