version: '3.8'
services:
    db:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: 'migration'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'migration_test'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password@123'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password@123'
        ports:
            # <Port exposed> : <MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - db:/var/lib/mysql
# Names our volume
volumes:
    db: