# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master", "release/*" ]
  pull_request:
    branches: [ "master", "release/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    env:
      ENVIRONMENT: ${{ vars.environment }}
      POSTGRES_DB: ${{ vars.postgres_db }}
      POSTGRES_USER: ${{ vars.postgres_user }}
      POSTGRES_PASSWORD: ${{ secrets.postgres_password }}
      MYSQL_USER: ${{ vars.mysql_user }}
      MYSQL_DATABASE: ${{ vars.mysql_database }}
      MYSQL_PASSWORD: ${{ secrets.mysql_password }}
      MYSQL_ROOT_PASSWORD: ${{ secrets.mysql_root_password }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build MySQL database container
      run: docker-compose -f ci/docker-compose.test.yml up -d
    
    - name: Install dependencies
      run: go mod tidy && go mod vendor

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
